<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KARTING.Domain\KARTING.Domain.csproj" />
        <ProjectReference Include="..\KARTING.ValueObjects\Domain.ValueObjects.csproj" />
        <ProjectReference Include="..\KARTING.Domain.Repositories.Abstractions\KARTING.Domain.Repositories.Abstractions.csproj" />
    </ItemGroup>

</Project>